<index.html>
<html lang="en">
<head>
<meta chargeset="UtF-8">
<meta name="viewport"content="width=devi-width. inital-scale1">
<title>Today'sData<title>
<meta name="geo.region" content=
<title> </title>
<meta http-equiv="X-UA-Compatible" content="IE=edge"><script type="text/javascript">(window.NREUM||(NREUM={})).init={ajax:{deny_list:["bam.nr-data.net"]}};(window.NREUM||(NREUM={})).loader_config={licenseKey:"1e7946724e",applicationID:"31671751"};;(()=>{var e,t,r={}
<!-- Google Tag Manager -->

<script> (function (w,d,s,1,i) (w[1]-[1]|| [];w[1].push({'gtm.start':

-new Date().getTime(), event: 'gtm.js'));var f=d.getElementsByTagName(s)[0],

j=d.createElement(s),dl=l!='dataLayer'?'1='+1:;j.async=true;j.src=

https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore (3,f):

-})(window,document, 'script', 'dataLayer', 'G-ZFDZXNBY1D');</script>

<!-- End Google Tag Manager -->
</nav>
      </div>
<title>google analytics</title>
</head>

<body>
<!-- Google Tag Manager (noscript)--> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=G-ZFDZXNBY1D')" -height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript> -- End Google Tag Manager (noscript) -->
body>

</html>



























   



    
     
     
   


  
  

    
   
    
       
 
    
   
     
     
